<?xml version="1.0" encoding="UTF-8"?>

<FLOW VERSION="3.0" CLEANUP="true">
  <COMMENT></COMMENT>

  <!-- nodes -->

<SEQUENCE TIMEOUT="" EXIT-ON="FAILURE" FORM="TRY">
  <COMMENT></COMMENT>

  <!-- nodes -->

<INVOKE TIMEOUT="" SERVICE="wx.resilienceTest.impl:subSubService" VALIDATE-IN="$none" VALIDATE-OUT="$none">
  <COMMENT></COMMENT>
</INVOKE>
</SEQUENCE>

<SEQUENCE TIMEOUT="" EXIT-ON="FAILURE" FORM="CATCH">
  <COMMENT></COMMENT>

  <!-- nodes -->

<INVOKE TIMEOUT="" SERVICE="pub.flow:getLastError" VALIDATE-IN="$none" VALIDATE-OUT="$none">
  <COMMENT></COMMENT>
</INVOKE>

<INVOKE TIMEOUT="" SERVICE="wx.resilience.pub.resilience:handleError" VALIDATE-IN="$none" VALIDATE-OUT="$none">
  <COMMENT></COMMENT>

  <!-- nodes -->

<MAP MODE="INPUT">
</MAP>

<MAP MODE="OUTPUT">
</MAP>
</INVOKE>
</SEQUENCE>

<SEQUENCE TIMEOUT="" EXIT-ON="FAILURE" FORM="FINALLY">
  <COMMENT></COMMENT>

  <!-- nodes -->

<INVOKE TIMEOUT="" SERVICE="wx.resilience.pub.resilience:throwExceptionIfNecessary" VALIDATE-IN="$none" VALIDATE-OUT="$none">
  <COMMENT></COMMENT>
</INVOKE>
</SEQUENCE>
</FLOW>
